version: '3'

services:
  postgres:
    container_name: postgres_tech_task
    image: postgres:12.1-alpine
    logging:
      driver: none
    #volumes:
    #  - ./postgres:/var/lib/postgresql/data:rw
    #ports:
    #  - 5432:5432
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass

  django:
    container_name: django_tech_task
    build: ./
    entrypoint: ./entrypoint.sh
    volumes:
      - ./src:/src:rw
      - ./.env:/src/core/.env
    depends_on:
      - postgres
    ports:
      - 8000:8000
    environment:
      MODE: DEV
      test: "pytest -v --cov . --cov-report term-missing
      --cov-fail-under=100 --flake8 -n 6 --no-migrations
      --reuse-db"
      # TODO: append "-W error" to $test
      #-W error"
      makemigrations: python manage.py makemigrations
      migrate: python manage.py migrate
      makemessages: python manage.py makemessages
      compilemessages: python manage.py compilemessages
      outdated: pip list --outdated --format=columns
      bandit: bandit -r .
      safety: safety check
      check: python manage.py check --deploy
      shell: python manage.py shell_plus
      createsuperuser: "python manage.py createsuperuser
      --username=aslanamanzholov
      --email=fenixx977@gmail.com"
