# Generated by Django 2.2.8 on 2020-08-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_topic', models.CharField(blank=True, max_length=250, null=True)),
                ('description_of_topic', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'db_table': 'topics',
                'ordering': ['-id'],
            },
        ),
    ]
