# Generated by Django 2.2.8 on 2020-08-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
