# Generated by Django 2.2.8 on 2020-08-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_topic_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
